#ifndef CLIENT_H
#define CLIENT_H

#include <iostream>
#include <memory>
#include <vector>

using namespace std;

class Client;
typedef shared_ptr<Client> ClientPtr;
typedef vector<ClientPtr> ClientList;

class Client
{
	long long client_id; //key: PRI
	long long sys_userid;
	long long sys_groupid;
	std::string sys_perm_user;
	std::string sys_perm_group;
	std::string sys_perm_other;
	std::string company_name;
	std::string company_id;
	std::string gender;
	std::string contact_name;
	std::string customer_no;
	std::string vat_id;
	std::string street;
	std::string zip;
	std::string city;
	std::string state;
	std::string country;
	std::string telephone;
	std::string mobile;
	std::string fax;
	std::string email;
	std::string internet;
	std::string icq;
	std::string notes;
	std::string bank_account_owner;
	std::string bank_account_number;
	std::string bank_code;
	std::string bank_name;
	std::string bank_account_iban;
	std::string bank_account_swift;
	std::string paypal_email;
	long long default_mailserver;
	std::string mail_servers;
	int limit_maildomain;
	int limit_mailbox;
	int limit_mailalias;
	int limit_mailaliasdomain;
	int limit_mailforward;
	int limit_mailcatchall;
	int limit_mailrouting;
	int limit_mailfilter;
	int limit_fetchmail;
	int limit_mailquota;
	int limit_spamfilter_wblist;
	int limit_spamfilter_user;
	int limit_spamfilter_policy;
	long long default_webserver;
	std::string web_servers;
	std::string limit_web_ip;
	int limit_web_domain;
	int limit_web_quota;
	std::string web_php_options;
	std::string limit_cgi;
	std::string limit_ssi;
	std::string limit_perl;
	std::string limit_ruby;
	std::string limit_python;
	std::string force_suexec;
	std::string limit_hterror;
	std::string limit_wildcard;
	std::string limit_ssl;
	int limit_web_subdomain;
	int limit_web_aliasdomain;
	int limit_ftp_user;
	int limit_shell_user;
	std::string ssh_chroot;
	int limit_webdav_user;
	std::string limit_backup;
	int limit_aps;
	long long default_dnsserver;
	std::string db_servers;
	int limit_dns_zone;
	long long default_slave_dnsserver;
	int limit_dns_slave_zone;
	int limit_dns_record;
	int default_dbserver;
	std::string dns_servers;
	int limit_database;
	int limit_database_quota;
	int limit_cron;
	std::string limit_cron_type;
	int limit_cron_frequency;
	int limit_traffic_quota;
	int limit_client;
	int limit_domainmodule;
	int limit_mailmailinglist;
	int limit_openvz_vm;
	int limit_openvz_vm_template_id;
	long long parent_client_id;
	std::string username;
	std::string password;
	std::string language;
	std::string usertheme;
	long long template_master;
	std::string template_additional;
	long long created_at;
	std::string locked;
	std::string canceled;
	std::string can_use_api;
	std::string tmp_data;
	std::string id_rsa;
	std::string ssh_rsa;
	std::string customer_no_template;
	int customer_no_start;
	int customer_no_counter;
	tm added_date;
	std::string added_by;
public:
	Client();
	Client(long long client_id);
	void init();
	long long getClientId() const;
	void setClientId(long long value);
	long long getSysUserid() const;
	void setSysUserid(long long value);
	long long getSysGroupid() const;
	void setSysGroupid(long long value);
	std::string getSysPermUser() const;
	void setSysPermUser(std::string value);
	std::string getSysPermGroup() const;
	void setSysPermGroup(std::string value);
	std::string getSysPermOther() const;
	void setSysPermOther(std::string value);
	std::string getCompanyName() const;
	void setCompanyName(std::string value);
	std::string getCompanyId() const;
	void setCompanyId(std::string value);
	std::string getGender() const;
	void setGender(std::string value);
	std::string getContactName() const;
	void setContactName(std::string value);
	std::string getCustomerNo() const;
	void setCustomerNo(std::string value);
	std::string getVatId() const;
	void setVatId(std::string value);
	std::string getStreet() const;
	void setStreet(std::string value);
	std::string getZip() const;
	void setZip(std::string value);
	std::string getCity() const;
	void setCity(std::string value);
	std::string getState() const;
	void setState(std::string value);
	std::string getCountry() const;
	void setCountry(std::string value);
	std::string getTelephone() const;
	void setTelephone(std::string value);
	std::string getMobile() const;
	void setMobile(std::string value);
	std::string getFax() const;
	void setFax(std::string value);
	std::string getEmail() const;
	void setEmail(std::string value);
	std::string getInternet() const;
	void setInternet(std::string value);
	std::string getIcq() const;
	void setIcq(std::string value);
	std::string getNotes() const;
	void setNotes(std::string value);
	std::string getBankAccountOwner() const;
	void setBankAccountOwner(std::string value);
	std::string getBankAccountNumber() const;
	void setBankAccountNumber(std::string value);
	std::string getBankCode() const;
	void setBankCode(std::string value);
	std::string getBankName() const;
	void setBankName(std::string value);
	std::string getBankAccountIban() const;
	void setBankAccountIban(std::string value);
	std::string getBankAccountSwift() const;
	void setBankAccountSwift(std::string value);
	std::string getPaypalEmail() const;
	void setPaypalEmail(std::string value);
	long long getDefaultMailserver() const;
	void setDefaultMailserver(long long value);
	std::string getMailServers() const;
	void setMailServers(std::string value);
	int getLimitMaildomain() const;
	void setLimitMaildomain(int value);
	int getLimitMailbox() const;
	void setLimitMailbox(int value);
	int getLimitMailalias() const;
	void setLimitMailalias(int value);
	int getLimitMailaliasdomain() const;
	void setLimitMailaliasdomain(int value);
	int getLimitMailforward() const;
	void setLimitMailforward(int value);
	int getLimitMailcatchall() const;
	void setLimitMailcatchall(int value);
	int getLimitMailrouting() const;
	void setLimitMailrouting(int value);
	int getLimitMailfilter() const;
	void setLimitMailfilter(int value);
	int getLimitFetchmail() const;
	void setLimitFetchmail(int value);
	int getLimitMailquota() const;
	void setLimitMailquota(int value);
	int getLimitSpamfilterWblist() const;
	void setLimitSpamfilterWblist(int value);
	int getLimitSpamfilterUser() const;
	void setLimitSpamfilterUser(int value);
	int getLimitSpamfilterPolicy() const;
	void setLimitSpamfilterPolicy(int value);
	long long getDefaultWebserver() const;
	void setDefaultWebserver(long long value);
	std::string getWebServers() const;
	void setWebServers(std::string value);
	std::string getLimitWebIp() const;
	void setLimitWebIp(std::string value);
	int getLimitWebDomain() const;
	void setLimitWebDomain(int value);
	int getLimitWebQuota() const;
	void setLimitWebQuota(int value);
	std::string getWebPhpOptions() const;
	void setWebPhpOptions(std::string value);
	std::string getLimitCgi() const;
	void setLimitCgi(std::string value);
	std::string getLimitSsi() const;
	void setLimitSsi(std::string value);
	std::string getLimitPerl() const;
	void setLimitPerl(std::string value);
	std::string getLimitRuby() const;
	void setLimitRuby(std::string value);
	std::string getLimitPython() const;
	void setLimitPython(std::string value);
	std::string getForceSuexec() const;
	void setForceSuexec(std::string value);
	std::string getLimitHterror() const;
	void setLimitHterror(std::string value);
	std::string getLimitWildcard() const;
	void setLimitWildcard(std::string value);
	std::string getLimitSsl() const;
	void setLimitSsl(std::string value);
	int getLimitWebSubdomain() const;
	void setLimitWebSubdomain(int value);
	int getLimitWebAliasdomain() const;
	void setLimitWebAliasdomain(int value);
	int getLimitFtpUser() const;
	void setLimitFtpUser(int value);
	int getLimitShellUser() const;
	void setLimitShellUser(int value);
	std::string getSshChroot() const;
	void setSshChroot(std::string value);
	int getLimitWebdavUser() const;
	void setLimitWebdavUser(int value);
	std::string getLimitBackup() const;
	void setLimitBackup(std::string value);
	int getLimitAps() const;
	void setLimitAps(int value);
	long long getDefaultDnsserver() const;
	void setDefaultDnsserver(long long value);
	std::string getDbServers() const;
	void setDbServers(std::string value);
	int getLimitDnsZone() const;
	void setLimitDnsZone(int value);
	long long getDefaultSlaveDnsserver() const;
	void setDefaultSlaveDnsserver(long long value);
	int getLimitDnsSlaveZone() const;
	void setLimitDnsSlaveZone(int value);
	int getLimitDnsRecord() const;
	void setLimitDnsRecord(int value);
	int getDefaultDbserver() const;
	void setDefaultDbserver(int value);
	std::string getDnsServers() const;
	void setDnsServers(std::string value);
	int getLimitDatabase() const;
	void setLimitDatabase(int value);
	int getLimitDatabaseQuota() const;
	void setLimitDatabaseQuota(int value);
	int getLimitCron() const;
	void setLimitCron(int value);
	std::string getLimitCronType() const;
	void setLimitCronType(std::string value);
	int getLimitCronFrequency() const;
	void setLimitCronFrequency(int value);
	int getLimitTrafficQuota() const;
	void setLimitTrafficQuota(int value);
	int getLimitClient() const;
	void setLimitClient(int value);
	int getLimitDomainmodule() const;
	void setLimitDomainmodule(int value);
	int getLimitMailmailinglist() const;
	void setLimitMailmailinglist(int value);
	int getLimitOpenvzVm() const;
	void setLimitOpenvzVm(int value);
	int getLimitOpenvzVmTemplateId() const;
	void setLimitOpenvzVmTemplateId(int value);
	long long getParentClientId() const;
	void setParentClientId(long long value);
	std::string getUsername() const;
	void setUsername(std::string value);
	std::string getPassword() const;
	void setPassword(std::string value);
	std::string getLanguage() const;
	void setLanguage(std::string value);
	std::string getUsertheme() const;
	void setUsertheme(std::string value);
	long long getTemplateMaster() const;
	void setTemplateMaster(long long value);
	std::string getTemplateAdditional() const;
	void setTemplateAdditional(std::string value);
	long long getCreatedAt() const;
	void setCreatedAt(long long value);
	std::string getLocked() const;
	void setLocked(std::string value);
	std::string getCanceled() const;
	void setCanceled(std::string value);
	std::string getCanUseApi() const;
	void setCanUseApi(std::string value);
	std::string getTmpData() const;
	void setTmpData(std::string value);
	std::string getIdRsa() const;
	void setIdRsa(std::string value);
	std::string getSshRsa() const;
	void setSshRsa(std::string value);
	std::string getCustomerNoTemplate() const;
	void setCustomerNoTemplate(std::string value);
	int getCustomerNoStart() const;
	void setCustomerNoStart(int value);
	int getCustomerNoCounter() const;
	void setCustomerNoCounter(int value);
	tm getAddedDate() const;
	void setAddedDate(tm value);
	std::string getAddedBy() const;
	void setAddedBy(std::string value);
};



#endif // CLIENT_H
