#ifndef WEBDOMAIN_H
#define WEBDOMAIN_H

#include <iostream>
#include <memory>
#include <vector>

using namespace std;

class WebDomain;
typedef shared_ptr<WebDomain> WebDomainPtr;
typedef vector<WebDomainPtr> WebDomainList;

class WebDomain
{
	long long domain_id; //key: PRI
	long long sys_userid;
	long long sys_groupid;
	std::string sys_perm_user;
	std::string sys_perm_group;
	std::string sys_perm_other;
	long long server_id; //key: MUL
	std::string ip_address;
	std::string ipv6_address;
	std::string domain;
	std::string type;
	long long parent_domain_id;
	std::string vhost_type;
	std::string document_root;
	std::string web_folder;
	std::string system_user;
	std::string system_group;
	long long hd_quota;
	long long traffic_quota;
	std::string cgi;
	std::string ssi;
	std::string suexec;
	int errordocs;
	int is_subdomainwww;
	std::string subdomain;
	std::string php;
	std::string ruby;
	std::string python;
	std::string perl;
	std::string redirect_type;
	std::string redirect_path;
	std::string seo_redirect;
	std::string ssl;
	std::string ssl_state;
	std::string ssl_locality;
	std::string ssl_organisation;
	std::string ssl_organisation_unit;
	std::string ssl_country;
	std::string ssl_domain;
	std::string ssl_request;
	std::string ssl_cert;
	std::string ssl_bundle;
	std::string ssl_key;
	std::string ssl_action;
	std::string stats_password;
	std::string stats_type;
	std::string allow_override;
	std::string apache_directives;
	std::string nginx_directives;
	std::string php_fpm_use_socket;
	std::string pm;
	int pm_max_children;
	int pm_start_servers;
	int pm_min_spare_servers;
	int pm_max_spare_servers;
	int pm_process_idle_timeout;
	int pm_max_requests;
	std::string php_open_basedir;
	std::string custom_php_ini;
	std::string backup_interval;
	int backup_copies;
	std::string backup_excludes;
	std::string active;
	std::string traffic_quota_lock;
	std::string fastcgi_php_version;
	std::string proxy_directives;
	tm last_quota_notification;
	std::string rewrite_rules;
	tm added_date;
	std::string added_by;
public:
	WebDomain();
	WebDomain(long long domain_id);
	void init();
	long long getDomainId() const;
	void setDomainId(long long value);
	long long getSysUserid() const;
	void setSysUserid(long long value);
	long long getSysGroupid() const;
	void setSysGroupid(long long value);
	std::string getSysPermUser() const;
	void setSysPermUser(std::string value);
	std::string getSysPermGroup() const;
	void setSysPermGroup(std::string value);
	std::string getSysPermOther() const;
	void setSysPermOther(std::string value);
	long long getServerId() const;
	void setServerId(long long value);
	std::string getIpAddress() const;
	void setIpAddress(std::string value);
	std::string getIpv6Address() const;
	void setIpv6Address(std::string value);
	std::string getDomain() const;
	void setDomain(std::string value);
	std::string getType() const;
	void setType(std::string value);
	long long getParentDomainId() const;
	void setParentDomainId(long long value);
	std::string getVhostType() const;
	void setVhostType(std::string value);
	std::string getDocumentRoot() const;
	void setDocumentRoot(std::string value);
	std::string getWebFolder() const;
	void setWebFolder(std::string value);
	std::string getSystemUser() const;
	void setSystemUser(std::string value);
	std::string getSystemGroup() const;
	void setSystemGroup(std::string value);
	long long getHdQuota() const;
	void setHdQuota(long long value);
	long long getTrafficQuota() const;
	void setTrafficQuota(long long value);
	std::string getCgi() const;
	void setCgi(std::string value);
	std::string getSsi() const;
	void setSsi(std::string value);
	std::string getSuexec() const;
	void setSuexec(std::string value);
	int getErrordocs() const;
	void setErrordocs(int value);
	int getIsSubdomainwww() const;
	void setIsSubdomainwww(int value);
	std::string getSubdomain() const;
	void setSubdomain(std::string value);
	std::string getPhp() const;
	void setPhp(std::string value);
	std::string getRuby() const;
	void setRuby(std::string value);
	std::string getPython() const;
	void setPython(std::string value);
	std::string getPerl() const;
	void setPerl(std::string value);
	std::string getRedirectType() const;
	void setRedirectType(std::string value);
	std::string getRedirectPath() const;
	void setRedirectPath(std::string value);
	std::string getSeoRedirect() const;
	void setSeoRedirect(std::string value);
	std::string getSsl() const;
	void setSsl(std::string value);
	std::string getSslState() const;
	void setSslState(std::string value);
	std::string getSslLocality() const;
	void setSslLocality(std::string value);
	std::string getSslOrganisation() const;
	void setSslOrganisation(std::string value);
	std::string getSslOrganisationUnit() const;
	void setSslOrganisationUnit(std::string value);
	std::string getSslCountry() const;
	void setSslCountry(std::string value);
	std::string getSslDomain() const;
	void setSslDomain(std::string value);
	std::string getSslRequest() const;
	void setSslRequest(std::string value);
	std::string getSslCert() const;
	void setSslCert(std::string value);
	std::string getSslBundle() const;
	void setSslBundle(std::string value);
	std::string getSslKey() const;
	void setSslKey(std::string value);
	std::string getSslAction() const;
	void setSslAction(std::string value);
	std::string getStatsPassword() const;
	void setStatsPassword(std::string value);
	std::string getStatsType() const;
	void setStatsType(std::string value);
	std::string getAllowOverride() const;
	void setAllowOverride(std::string value);
	std::string getApacheDirectives() const;
	void setApacheDirectives(std::string value);
	std::string getNginxDirectives() const;
	void setNginxDirectives(std::string value);
	std::string getPhpFpmUseSocket() const;
	void setPhpFpmUseSocket(std::string value);
	std::string getPm() const;
	void setPm(std::string value);
	int getPmMaxChildren() const;
	void setPmMaxChildren(int value);
	int getPmStartServers() const;
	void setPmStartServers(int value);
	int getPmMinSpareServers() const;
	void setPmMinSpareServers(int value);
	int getPmMaxSpareServers() const;
	void setPmMaxSpareServers(int value);
	int getPmProcessIdleTimeout() const;
	void setPmProcessIdleTimeout(int value);
	int getPmMaxRequests() const;
	void setPmMaxRequests(int value);
	std::string getPhpOpenBasedir() const;
	void setPhpOpenBasedir(std::string value);
	std::string getCustomPhpIni() const;
	void setCustomPhpIni(std::string value);
	std::string getBackupInterval() const;
	void setBackupInterval(std::string value);
	int getBackupCopies() const;
	void setBackupCopies(int value);
	std::string getBackupExcludes() const;
	void setBackupExcludes(std::string value);
	std::string getActive() const;
	void setActive(std::string value);
	std::string getTrafficQuotaLock() const;
	void setTrafficQuotaLock(std::string value);
	std::string getFastcgiPhpVersion() const;
	void setFastcgiPhpVersion(std::string value);
	std::string getProxyDirectives() const;
	void setProxyDirectives(std::string value);
	tm getLastQuotaNotification() const;
	void setLastQuotaNotification(tm value);
	std::string getRewriteRules() const;
	void setRewriteRules(std::string value);
	tm getAddedDate() const;
	void setAddedDate(tm value);
	std::string getAddedBy() const;
	void setAddedBy(std::string value);
};



#endif // WEBDOMAIN_H
